import {
  createElement, PencilLine, LockKeyhole, ImageOff, Expand, ImagePlus,
  LoaderCircle, FolderOpen, AlignHorizontalSpaceAround, AlignVerticalSpaceAround, Archive, ArrowRight,
  ArrowRightFromLine, ArrowUp, AudioLines, AudioWaveform, BadgeCheck, BookOpen,
  BookOpenCheck, Bot, Box, Building2, CalendarDays, Check,
  ChevronDown, ChevronLeft, ChevronRight, ChevronsRight, Circle, CircleAlert, CircleDollarSign,
  CircleHelp, CircleMinus, CirclePlay, Clock, Combine, Copy,
  CopyCheck, Crop, Download, Ellipsis, EllipsisVertical, Eraser,
  Eye, FilterX, Focus, Folder, FolderInput,
  FolderPlus, Folders, Gauge, Grid2x2, Grid3x3, Hd,
  House, Image, Images, Info, Keyboard, Layers2,
  Layers3, LayoutGrid, List, ListChecks, ListFilter, WandSparkles,
  LocateFixed, LogOut, Map, Maximize, Maximize2, MessageSquarePlus,
  Minimize, Minimize2, Monitor, Moon, MousePointer2, MousePointerClick,
  Music2, NotepadTextDashed, PanelLeftClose, PanelsTopLeft, Paperclip,
  Pause, Pen, Pencil, Pin, PinOff, Play,
  Plus, RefreshCw, RotateCcw, RotateCw, ScanLine, ScanSearch,
  Scissors, Search, SearchX, SendHorizontal, Settings, Settings2,
  Share2, ShieldCheck, SlidersHorizontal, Sparkles, Square, SquareCheckBig,
  SquarePen, SquarePlay, SquarePlus, SquareUserRound, Sun, Timer,
  Trash2, Type, Ungroup, Upload, UserRound, UserRoundPlus,
  Users, UsersRound, Video, Volume2, VolumeX, Workflow,
  X, CircleUserRound, LibraryBig, PanelRightClose, Tags,
} from "lucide";

// Import only the icons used by the canvas. Historical names map to official icons.
const icons = Object.freeze({
  "tags": Tags,
  "circle-user-round": CircleUserRound,
  "library-big": LibraryBig,
  "panel-right-close": PanelRightClose,
  "pencil-line": PencilLine,
  "lock-keyhole": LockKeyhole,
  "image-off": ImageOff,
  "expand": Expand,
  "image-plus": ImagePlus,
  "loader-circle": LoaderCircle,
  "folder-open": FolderOpen,
  "align-horizontal-space-around": AlignHorizontalSpaceAround,
  "align-vertical-space-around": AlignVerticalSpaceAround,
  "archive": Archive,
  "arrow-right": ArrowRight,
  "arrow-right-from-line": ArrowRightFromLine,
  "arrow-up": ArrowUp,
  "audio-lines": AudioLines,
  "audio-waveform": AudioWaveform,
  "badge-check": BadgeCheck,
  "badge-hd": Hd,
  "book-open": BookOpen,
  "book-open-check": BookOpenCheck,
  "bot": Bot,
  "box": Box,
  "building-2": Building2,
  "calendar-days": CalendarDays,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevrons-right": ChevronsRight,
  "circle": Circle,
  "circle-alert": CircleAlert,
  "circle-dollar-sign": CircleDollarSign,
  "circle-help": CircleHelp,
  "circle-minus": CircleMinus,
  "circle-play": CirclePlay,
  "clock": Clock,
  "combine": Combine,
  "copy": Copy,
  "copy-check": CopyCheck,
  "crop": Crop,
  "download": Download,
  "ellipsis": Ellipsis,
  "ellipsis-vertical": EllipsisVertical,
  "eraser": Eraser,
  "eye": Eye,
  "filter-x": FilterX,
  "focus": Focus,
  "folder": Folder,
  "folder-input": FolderInput,
  "folder-plus": FolderPlus,
  "folders": Folders,
  "gauge": Gauge,
  "grid-2x2": Grid2x2,
  "grid-3x3": Grid3x3,
  "house": House,
  "image": Image,
  "images": Images,
  "info": Info,
  "keyboard": Keyboard,
  "layers-2": Layers2,
  "layers-3": Layers3,
  "layout-grid": LayoutGrid,
  "list": List,
  "list-checks": ListChecks,
  "list-filter": ListFilter,
  "wand-sparkles": WandSparkles,
  "locate-fixed": LocateFixed,
  "log-out": LogOut,
  "map": Map,
  "maximize": Maximize,
  "maximize-2": Maximize2,
  "message-square-plus": MessageSquarePlus,
  "minimize": Minimize,
  "minimize-2": Minimize2,
  "monitor": Monitor,
  "moon": Moon,
  "more-horizontal": Ellipsis,
  "mouse-pointer-2": MousePointer2,
  "mouse-pointer-click": MousePointerClick,
  "music-2": Music2,
  "notepad-text-dashed": NotepadTextDashed,
  "panel-left-close": PanelLeftClose,
  "panels-top-left": PanelsTopLeft,
  "paperclip": Paperclip,
  "pause": Pause,
  "pen": Pen,
  "pencil": Pencil,
  "pin": Pin,
  "pin-off": PinOff,
  "play": Play,
  "play-square": SquarePlay,
  "plus": Plus,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "scan": ScanLine,
  "scan-search": ScanSearch,
  "scissors": Scissors,
  "search": Search,
  "search-x": SearchX,
  "send-horizontal": SendHorizontal,
  "settings": Settings,
  "settings-2": Settings2,
  "share-2": Share2,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  "sparkles": Sparkles,
  "square": Square,
  "square-check-big": SquareCheckBig,
  "square-pen": SquarePen,
  "square-play": SquarePlay,
  "square-plus": SquarePlus,
  "square-user-round": SquareUserRound,
  "sun": Sun,
  "timer": Timer,
  "trash-2": Trash2,
  "type": Type,
  "ungroup": Ungroup,
  "upload": Upload,
  "user-round": UserRound,
  "user-round-plus": UserRoundPlus,
  "users": Users,
  "users-round": UsersRound,
  "video": Video,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "workflow": Workflow,
  "x": X,
});

function create(name, attributes = {}) {
  const definition = icons[name];
  if (!definition) throw new Error(`Unknown canvas icon: ${name}`);
  return createElement(definition, {
    "aria-hidden": "true", focusable: "false", "stroke-width": 1.8,
    ...attributes, class: ["lucide", `lucide-${name}`, attributes.class].filter(Boolean).join(" "),
  });
}

function markup(name, attributes = {}) { return create(name, attributes).outerHTML; }

function refresh(root = document) {
  const placeholders = [...root.querySelectorAll("i[data-lucide]")];
  if (root.matches?.("i[data-lucide]")) placeholders.unshift(root);
  for (const placeholder of placeholders) {
    const attributes = Object.fromEntries([...placeholder.attributes].map(({ name, value }) => [name, value]));
    delete attributes["data-lucide"];
    placeholder.replaceWith(create(placeholder.dataset.lucide, attributes));
  }
}

window.REELAY_ICONS = Object.freeze({ create, markup, refresh });
