(function defineReelayPrototypeConfig() {
  const imageResolutionCost = {
    "1024px": 3,
    "1K": 3,
    "2K": 5,
    "4K": 9,
  };

  const imageQualityMultiplier = {
    低: 0.7,
    中: 1,
    高: 1.8,
  };

  const videoQualityCost = {
    "480p": 8,
    "720p": 12,
    "1080p": 18,
    "4K": 36,
  };

  const simulationAssets = {
    image: {
      type: "image",
      name: "Reelay simulated image",
      displayName: "Generated image",
      url: "https://picsum.photos/seed/reelay-canvas/1280/720",
      width: 1280,
      height: 720,
      aspectRatio: 16 / 9,
    },
    video: {
      type: "video",
      name: "Reelay simulated video",
      displayName: "Generated video",
      url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
      width: 1280,
      height: 720,
      aspectRatio: 16 / 9,
    },
  };

  const assetLibrarySeed = {
    media: [
      {
        id: "media-personal-mountain",
        mediaKind: "image",
        type: "image",
        name: "森林旅人.webp",
        displayName: "森林旅人.webp",
        url: "./assets/home/project-character.webp",
        width: 800,
        height: 450,
        aspectRatio: 16 / 9,
        source: "upload",
      },
      {
        id: "media-personal-umbra-key-art",
        mediaKind: "image",
        type: "image",
        name: "幽影_01_角色主视觉.jpg",
        displayName: "幽影_01_角色主视觉.jpg",
        contentType: "image/jpeg",
        url: "./assets/home/entity-umbra-01-key-art-v4.jpg",
        width: 1500,
        height: 1924,
        aspectRatio: 0.7796257796257796,
        source: "upload",
      },
      {
        id: "media-personal-umbra-character-sheet",
        mediaKind: "image",
        type: "image",
        name: "幽影_02_角色多视图.png",
        displayName: "幽影_02_角色多视图.png",
        contentType: "image/png",
        url: "./assets/home/entity-umbra-02-character-sheet-v4.png",
        width: 2048,
        height: 1152,
        aspectRatio: 1.7777777777777777,
        source: "upload",
      },
      {
        id: "media-personal-umbra-concept-sketches",
        mediaKind: "image",
        type: "image",
        name: "幽影_03_概念草图.jpg",
        displayName: "幽影_03_概念草图.jpg",
        contentType: "image/jpeg",
        url: "./assets/home/entity-umbra-03-concept-sketches-v4.jpg",
        width: 1920,
        height: 831,
        aspectRatio: 2.3104693140794224,
        source: "upload",
      },
      {
        id: "media-personal-umbra-chain-blades",
        mediaKind: "image",
        type: "image",
        name: "幽影_04_链刃武器设定.png",
        displayName: "幽影_04_链刃武器设定.png",
        contentType: "image/png",
        url: "./assets/home/entity-umbra-04-chain-blades-v4.png",
        width: 2048,
        height: 1152,
        aspectRatio: 1.7777777777777777,
        source: "upload",
      },
      {
        id: "media-personal-umbra-energy-shield",
        mediaKind: "image",
        type: "image",
        name: "幽影_05_能量护盾特效.png",
        displayName: "幽影_05_能量护盾特效.png",
        contentType: "image/png",
        url: "./assets/home/entity-umbra-05-energy-shield-v4.png",
        width: 2048,
        height: 1152,
        aspectRatio: 1.7777777777777777,
        source: "upload",
      },
      {
        id: "media-personal-baixi-portrait",
        mediaKind: "image",
        type: "image",
        name: "白汐_01_角色肖像.png",
        displayName: "白汐_01_角色肖像.png",
        contentType: "image/png",
        url: "./assets/home/entity-baixi-01-portrait-v4.png",
        width: 1122,
        height: 1402,
        aspectRatio: 0.8002853067047075,
        source: "upload",
      },
      {
        id: "media-personal-baixi-turnaround",
        mediaKind: "image",
        type: "image",
        name: "白汐_02_角色三视图.png",
        displayName: "白汐_02_角色三视图.png",
        contentType: "image/png",
        url: "./assets/home/entity-baixi-02-turnaround-v4.png",
        width: 1448,
        height: 1086,
        aspectRatio: 1.3333333333333333,
        source: "upload",
      },
      {
        id: "media-personal-baixi-equipment",
        mediaKind: "image",
        type: "image",
        name: "白汐_03_随身装备设定.png",
        displayName: "白汐_03_随身装备设定.png",
        contentType: "image/png",
        url: "./assets/home/entity-baixi-03-equipment-v4.png",
        width: 1122,
        height: 1402,
        aspectRatio: 0.8002853067047075,
        source: "upload",
      },
      {
        id: "media-personal-xuanling-key-art",
        mediaKind: "image",
        type: "image",
        name: "玄翎_01_角色主视觉.png",
        displayName: "玄翎_01_角色主视觉.png",
        contentType: "image/png",
        url: "./assets/home/entity-xuanling-01-key-art-v4.png",
        width: 941,
        height: 1672,
        aspectRatio: 0.562799043062201,
        source: "upload",
      },
      {
        id: "media-personal-xuanling-character-sheet",
        mediaKind: "image",
        type: "image",
        name: "玄翎_02_角色多视图.png",
        displayName: "玄翎_02_角色多视图.png",
        contentType: "image/png",
        url: "./assets/home/entity-xuanling-02-character-sheet-v4.png",
        width: 1672,
        height: 941,
        aspectRatio: 1.7768331562167907,
        source: "upload",
      },
      {
        id: "media-personal-xuanling-costume-variations",
        mediaKind: "image",
        type: "image",
        name: "玄翎_03_服装造型变体.png",
        displayName: "玄翎_03_服装造型变体.png",
        contentType: "image/png",
        url: "./assets/home/entity-xuanling-03-costume-variations-v4.png",
        width: 1122,
        height: 1402,
        aspectRatio: 0.8002853067047075,
        source: "upload",
      },
      {
        id: "media-personal-xuanling-equipment",
        mediaKind: "image",
        type: "image",
        name: "玄翎_04_武器装备设定.png",
        displayName: "玄翎_04_武器装备设定.png",
        contentType: "image/png",
        url: "./assets/home/entity-xuanling-04-equipment-v4.png",
        width: 1122,
        height: 1402,
        aspectRatio: 0.8002853067047075,
        source: "upload",
      },
      {
        id: "media-personal-forest",
        mediaKind: "video",
        type: "video",
        name: "林间镜头.mp4",
        displayName: "林间镜头.mp4",
        url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
        width: 1280,
        height: 720,
        aspectRatio: 16 / 9,
        source: "generation-result",
      },
      {
        id: "media-personal-roar",
        mediaKind: "audio",
        type: "audio",
        name: "氛围低吼.mp3",
        displayName: "氛围低吼.mp3",
        url: "https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3",
        duration: 0,
        source: "upload",
      },
      {
        id: "media-organization-product",
        mediaKind: "image",
        type: "image",
        name: "品牌产品参考.png",
        displayName: "品牌产品参考.png",
        url: "./assets/home/project-product.webp",
        width: 800,
        height: 450,
        aspectRatio: 16 / 9,
        source: "team-shared",
      },
      {
        id: "media-platform-landscape",
        mediaKind: "image",
        type: "image",
        name: "深空母舰.webp",
        displayName: "深空母舰.webp",
        url: "./assets/home/project-scifi.webp",
        width: 800,
        height: 450,
        aspectRatio: 16 / 9,
        source: "platform",
        platformSourceId: "platform-landscape-001",
        sourceCatalogId: "reelay-inspiration",
      },
      {
        id: "media-platform-roar",
        mediaKind: "audio",
        type: "audio",
        name: "荒原巨兽低吼.mp3",
        displayName: "荒原巨兽低吼.mp3",
        url: "https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3",
        duration: 0,
        source: "platform",
        platformSourceId: "platform-roar-001",
        sourceCatalogId: "reelay-inspiration",
      },
    ],
    entities: [
      {
        id: "entity-personal-umbra",
        name: "幽影",
        description: "紫色兜帽与青色能量面甲的幽影战士；收录角色主视觉、多视图、概念草图、链刃武器与能量护盾设定。",
        mediaRefs: [
          { mediaId: "media-personal-umbra-key-art", order: 0 },
          { mediaId: "media-personal-umbra-character-sheet", order: 1 },
          { mediaId: "media-personal-umbra-concept-sketches", order: 2 },
          { mediaId: "media-personal-umbra-chain-blades", order: 3 },
          { mediaId: "media-personal-umbra-energy-shield", order: 4 },
        ],
        coverMediaId: "media-personal-umbra-key-art",
      },
      {
        id: "entity-personal-baixi",
        name: "白汐",
        description: "身着白色机能外套的短发探索者，以薄荷绿与橙色细节为识别特征；收录肖像、三视图与随身装备。",
        mediaRefs: [
          { mediaId: "media-personal-baixi-portrait", order: 0 },
          { mediaId: "media-personal-baixi-turnaround", order: 1 },
          { mediaId: "media-personal-baixi-equipment", order: 2 },
        ],
        coverMediaId: "media-personal-baixi-portrait",
      },
      {
        id: "entity-personal-xuanling",
        name: "玄翎",
        description: "穿行巨构遗迹的黑白金配色剑士，以长剑、束发与飘带构成角色轮廓；收录主视觉、多视图、服装变体与武器装备。",
        mediaRefs: [
          { mediaId: "media-personal-xuanling-key-art", order: 0 },
          { mediaId: "media-personal-xuanling-character-sheet", order: 1 },
          { mediaId: "media-personal-xuanling-costume-variations", order: 2 },
          { mediaId: "media-personal-xuanling-equipment", order: 3 },
        ],
        coverMediaId: "media-personal-xuanling-key-art",
      },
    ],
    folders: [
      { id: "folder-personal-visual", space: "personal", kind: "media", name: "视觉参考", parentId: null },
      { id: "folder-personal-entity", space: "personal", kind: "entity", name: "主体合集", parentId: null },
      { id: "folder-organization-brand", space: "organization", kind: "media", name: "品牌资料", parentId: null },
      { id: "folder-platform-starter", space: "platform", kind: "media", name: "平台示例", parentId: null },
    ],
    placements: [
      { item: { kind: "media", id: "media-personal-umbra-key-art" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-umbra-character-sheet" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-umbra-concept-sketches" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-umbra-chain-blades" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-umbra-energy-shield" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-baixi-portrait" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-baixi-turnaround" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-baixi-equipment" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-xuanling-key-art" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-xuanling-character-sheet" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-xuanling-costume-variations" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-xuanling-equipment" }, space: "personal", folderId: null },
      { item: { kind: "entity", id: "entity-personal-umbra" }, space: "personal", folderId: null },
      { item: { kind: "entity", id: "entity-personal-baixi" }, space: "personal", folderId: null },
      { item: { kind: "entity", id: "entity-personal-xuanling" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-mountain" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-forest" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-personal-roar" }, space: "personal", folderId: null },
      { item: { kind: "media", id: "media-organization-product" }, space: "organization", folderId: null },
      { item: { kind: "media", id: "media-platform-landscape" }, space: "platform", folderId: null },
      { item: { kind: "media", id: "media-platform-roar" }, space: "platform", folderId: null },
    ],
  };

  const mediaToolDefinitions = {
    enhance: { icon: "badge-hd", label: "HD 增强" },
    crop: { icon: "crop", label: "裁剪" },
    "remove-bg": { icon: "scan", label: "去背景" },
    eraser: { icon: "eraser", label: "橡皮擦" },
    adjust: { icon: "sliders-horizontal", label: "调整" },
    rotate: { icon: "rotate-cw", label: "旋转" },
    trim: { icon: "scissors", label: "裁剪片段" },
    interpolate: { icon: "gauge", label: "提升帧率" },
    denoise: { icon: "audio-waveform", label: "降噪" },
    "add-library": { icon: "folder-plus", label: "加入资产库" },
  };

  const mediaToolsByType = {
    image: ["enhance", "crop", "remove-bg", "eraser", "adjust", "rotate", "add-library"],
    video: ["enhance", "trim", "interpolate", "remove-bg", "adjust", "rotate", "add-library"],
    audio: ["enhance", "trim", "denoise", "adjust", "add-library"],
  };

  const defaultMediaToolPreferences = {
    image: { tools: ["enhance", "crop", "remove-bg", "add-library"], showLabels: false },
    video: { tools: ["enhance", "trim", "interpolate", "add-library"], showLabels: false },
    audio: { tools: ["enhance", "trim", "denoise", "add-library"], showLabels: false },
  };

  const generationWorkflows = {
    image: [],
    video: [
      { id: "text-to-video", label: "文生视频", icon: "square-play" },
      { id: "omni-reference", label: "全能参考", icon: "folder-plus" },
      { id: "first-last-frame", label: "首尾帧", icon: "panels-top-left" },
      { id: "image-to-video", label: "图生视频", icon: "image" },
    ],
  };

  const agentConversations = [
    {
      id: "new",
      title: "新对话",
      messages: [],
    },
    {
      id: "seedance",
      title: "你有多了解 Seedance 2.5 创作视频...",
      messages: [
        {
          role: "user",
          content: "我想把一个图片节点做成 4 秒的动态短片。",
        },
        {
          role: "agent",
          content: "可以先选择视频模型，再把图片素材拖进生成节点上方素材列。我会建议锁定比例、时长和镜头运动。",
        },
      ],
    },
    {
      id: "assets",
      title: "素材整理与生成节点规划",
      messages: [
        {
          role: "user",
          content: "帮我整理画布里的图片、视频和音频素材。",
        },
        {
          role: "agent",
          content: "可以按素材类型建立输入区，再用生成节点衔接输出。后续适合加素材筛选、引用关系和批量操作。",
        },
      ],
    },
  ];

  const layoutRules = {
    defaultRatio: 16 / 9,
    audioRatio: 5 / 2,
    landscapeWidth: 620,
    squareSize: 460,
    portraitHeight: 520,
    maxWidth: 660,
    maxHeight: 520,
    minMediaWidth: 300,
    minMediaHeight: 220,
    // Existing documents store x relative to this world-space container.
    // Editor density must never move the media anchor of a saved node.
    generatorAnchorWidth: 705,
    normalPanelHeight: 320,
    compactPanelHeight: 248,
    advancedSettingsHeightByMode: {
      image: 118,
      video: 118,
    },
    promptInputTop: 76,
    promptInputBottom: 60,
    promptScreenWidthByMode: { image: 850, video: 800 },
    promptScreenMargin: 24,
    panelGap: 12,
  };

  const canvasScaleLimits = {
    min: 0.2,
    max: 2,
  };

  const groupFrameRules = {
    paddingX: 46,
    paddingTop: 58,
    paddingBottom: 46,
    minWidth: 280,
    minHeight: 180,
  };

  window.REELAY_PROTOTYPE_CONFIG = {
    imageResolutionCost,
    imageQualityMultiplier,
    videoQualityCost,
    simulationAssets,
    assetLibrarySeed,
    mediaToolDefinitions,
    mediaToolsByType,
    defaultMediaToolPreferences,
    generationWorkflows,
    agentConversations,
    layoutRules,
    canvasScaleLimits,
    groupFrameRules,
  };
})();
